export const GET_TASKLIST_REQUEST = "GET_TASKLIST_REQUEST" 
export const GET_TASKLIST_SUCCESS = "GET_TASKLIST_SUCCESS" 
export const GET_TASKLIST_FAILURE = "GET_TASKLIST_FAILURE" 

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST" 
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS" 
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE" 

export const DEL_TASK_REQUEST = "DEL_TASK_REQUEST" 
export const DEL_TASK_SUCCESS = "DEL_TASK_SUCCESS" 
export const DEL_TASK_FAILURE = "DEL_TASK_FAILURE" 

export const CHANGE_STATUS_REQUEST = "CHANGE_STATUS_REQUEST" 
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS" 
export const CHANGE_STATUS_FAILURE = "CHANGE_STATUS_FAILURE" 

